Make deploy a command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,92 @@
 version: 2.0
+
+commands:
+  deploy:
+    description: "A very simple command for demonstration purposes"
+    parameters:
+      to:
+        type: string
+        default: "World"
+    working_directory: ~/project
+    docker:
+      - image: circleci/python:3.6-node
+    steps:
+      - checkout
+      - setup_remote_docker
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: Check deploy Authorisation
+          command: |
+            if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+              echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+              exit 1;
+            fi
+      - run:
+          name: Load Docker Images
+          command: |
+            docker load -i docker-cache/images.tar
+
+      - run:
+          name: Prepare for pyth venv install
+          command: |
+            sudo chown -R circleci:circleci /usr/local/bin
+            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
+      - restore_cache:
+          key: pydeps-v3-{{ .Branch }}-{{ checksum "~/project/.circleci/requirements.txt" }}
+      - run:
+          name: pip fix
+          command: curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python
+      - run:
+          name: Setup AWS CLI
+          command: |
+            pip install -r ~/project/.circleci/requirements.txt
+      - save_cache:
+          key: pydeps-v3-{{ .Branch }}-{{ checksum "~/project/.circleci/requirements.txt" }}
+          paths:
+            - ".venv"
+            - "/usr/local/bin"
+            - "/usr/local/lib/python3.6/site-packages"
+      - run:
+          name: Push Docker Image
+          command: |
+            eval $(aws ecr get-login --no-include-email --region ${REPOSITORY_REGION});
+            docker tag server:${CIRCLE_SHA1} ${APP_REPOSITORY_URI}:server_${CIRCLE_SHA1}
+            docker push ${APP_REPOSITORY_URI}:server_${CIRCLE_SHA1}
+            docker tag eth_worker:${CIRCLE_SHA1} ${WORKER_REPOSITORY_URI}:eth_worker_${CIRCLE_SHA1}
+            docker push ${WORKER_REPOSITORY_URI}:eth_worker_${CIRCLE_SHA1}
+      - run:
+          name: Add updated images to task definitions
+          command: |
+            sed "s|CIRCLE_SHA1|${CIRCLE_SHA1}|g;" ecs_app_task_config_template.json > ecs_app_task_config.json
+            sed "s|CIRCLE_SHA1|${CIRCLE_SHA1}|g;" ecs_worker_task_config_template.json > ecs_app_worker_config.json
+      - run:
+          name: Upload static assets to S3
+          command: |
+            aws s3 rm s3://sempo-dev-static/static --recursive
+            aws s3 sync app/server/static s3://sempo-dev-static/static
+      - run:
+          name: Remove old ECS task
+          command: |
+            aws ecs update-service --cluster devecs --service app --desired-count 0
+            aws ecs update-service --cluster devecs --service worker-ecs --desired-count 0
+      - run:
+          name: Update ECS Task
+          command: |
+            aws ecs register-task-definition --cli-input-json file://ecs_app_task_config.json
+            aws ecs register-task-definition --cli-input-json file://ecs_app_worker_config.json
+      - run:
+          name: Add capacity for new task
+          command: |
+            aws ecs update-service --cluster devecs --service app --desired-count 1
+            aws ecs update-service --cluster devecs --service worker-ecs --desired-count 1
+
+      - run:
+          name: Deploy
+          command: |
+            aws ecs update-service --cluster devecs --service app --task-definition app --force-new-deployment
+            aws ecs update-service --cluster devecs --service worker-ecs --task-definition worker --force-new-deployment
+
 jobs:
   build:
     working_directory: ~/project
@@ -145,81 +233,8 @@ jobs:
     docker:
       - image: circleci/python:3.6-node
     steps:
-      - checkout
-      - setup_remote_docker
-      - attach_workspace:
-          at: ~/project
-      - run:
-          name: Check deploy Authorisation
-          command: |
-            if [ -z "$AWS_ACCESS_KEY_ID" ]; then
-              echo "No AWS_ACCESS_KEY_ID is set! Failing..."
-              exit 1;
-            fi
-      - run:
-          name: Load Docker Images
-          command: |
-            docker load -i docker-cache/images.tar
-
-      - run:
-          name: Prepare for pyth venv install
-          command: |
-            sudo chown -R circleci:circleci /usr/local/bin
-            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
-      - restore_cache:
-          key: pydeps-v3-{{ .Branch }}-{{ checksum "~/project/.circleci/requirements.txt" }}
-      - run:
-          name: pip fix
-          command: curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python
-      - run:
-          name: Setup AWS CLI
-          command: |
-            pip install -r ~/project/.circleci/requirements.txt
-      - save_cache:
-          key: pydeps-v3-{{ .Branch }}-{{ checksum "~/project/.circleci/requirements.txt" }}
-          paths:
-            - ".venv"
-            - "/usr/local/bin"
-            - "/usr/local/lib/python3.6/site-packages"
-      - run:
-          name: Push Docker Image
-          command: |
-            eval $(aws ecr get-login --no-include-email --region ${REPOSITORY_REGION});
-            docker tag server:${CIRCLE_SHA1} ${APP_REPOSITORY_URI}:server_${CIRCLE_SHA1}
-            docker push ${APP_REPOSITORY_URI}:server_${CIRCLE_SHA1}
-            docker tag eth_worker:${CIRCLE_SHA1} ${WORKER_REPOSITORY_URI}:eth_worker_${CIRCLE_SHA1}
-            docker push ${WORKER_REPOSITORY_URI}:eth_worker_${CIRCLE_SHA1}
-      - run:
-          name: Add updated images to task definitions
-          command: |
-            sed "s|CIRCLE_SHA1|${CIRCLE_SHA1}|g;" ecs_app_task_config_template.json > ecs_app_task_config.json
-            sed "s|CIRCLE_SHA1|${CIRCLE_SHA1}|g;" ecs_worker_task_config_template.json > ecs_app_worker_config.json
-      - run:
-          name: Upload static assets to S3
-          command: |
-            aws s3 rm s3://sempo-dev-static/static --recursive
-            aws s3 sync app/server/static s3://sempo-dev-static/static
-      - run:
-          name: Remove old ECS task
-          command: |
-            aws ecs update-service --cluster devecs --service app --desired-count 0
-            aws ecs update-service --cluster devecs --service worker-ecs --desired-count 0
-      - run:
-          name: Update ECS Task
-          command: |
-            aws ecs register-task-definition --cli-input-json file://ecs_app_task_config.json
-            aws ecs register-task-definition --cli-input-json file://ecs_app_worker_config.json
-      - run:
-          name: Add capacity for new task
-          command: |
-            aws ecs update-service --cluster devecs --service app --desired-count 1
-            aws ecs update-service --cluster devecs --service worker-ecs --desired-count 1
-
-      - run:
-          name: Deploy
-          command: |
-            aws ecs update-service --cluster devecs --service app --task-definition app --force-new-deployment
-            aws ecs update-service --cluster devecs --service worker-ecs --task-definition worker --force-new-deployment
+      - deploy: # invoke command "sayhello"
+          to: "Lev"
 
 workflows:
   version: 2
@@ -240,6 +255,7 @@ workflows:
             branches:
               only:
                 - master
+                - ci-deploy-different-branches
           requires:
             - build
             - test:backend
